### ISSUE TITLE
some page could not be parsed

### ISSUE THREAD

**Issue by zhoufenfens** [tulios/json-viewer#108]
hi,thanks for your work on this extensions, it works well usually, but it could not work when it came across some page link [example link](http://106.38.230.147:8080/error/get)

**Comment by tulios** [comment]
Hi @zhoufenfens, the URL is returning `Content-Type:text/html;charset=UTF-8` that's why the extension is not been activated

**Comment by anotherdevs** [comment]
Hi

Will it possible to add an option that can enable the extension even if the content-type is not application/json?

Like the now removed extension JSON View.

**Comment by tulios** [comment]
This is possible. The only problem I see with this approach is that the extension will try to process all pages and this can introduce some delay in your navigation since it will try to parse every content. Maybe a better solution will be a whitelist, if it is JSON or belongs to this whitelist then the extention can be activate.

What do you think @anotherdevs?

**Comment by anotherdevs** [comment]
Hi again

Could be an option - however I will let it be up to your, since you are the expert on this plugin.
The original plugin, JSON View for Chrome, resides here: https://github.com/gildas-lormeau/JSONView-for-Chrome - with this plugin I really didn't notice any lag or delay in navigation. Maybe you can find any hints in the code?

It could be that you'll get a lot more users since his plugin has been banned from Chrome: https://github.com/gildas-lormeau/JSONView-for-Chrome/issues/75 and https://github.com/bhollis/jsonview/issues/135 and they are familiar with this behaviour.

A whitelist could be an option or accept the delay, but you'll need to activate it - with a warning shown, that it could decrease performance or increase delay in navigation.

**Comment by scudelletti** [comment]
Hi guys, 

Since this is based on the `Content-Type` we can hack this behaviour using other extension that can change the response `Content-Type`.

I tried using [ModeHeader extension](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj) and it worked fine. We can also apply the profile on specific urls due to the `filter` feature.

Here is a screenshot of the usage and configuration.
![screenshot](https://cloud.githubusercontent.com/assets/410080/20351249/5cd5491a-ac12-11e6-901a-045ed8cb0401.png)

APIs with wrong headers are evil. 😭

**Comment by zhoufenfens** [comment]
it is great :+1: :clap:

**Comment by zhoufenfens** [comment]
could the page's font size be changed? i think it is a little big.

**Comment by scudelletti** [comment]
The `ModeHeader` extension just change the headers, so you can continue using the `json-viewer` and there you can set the font-size and theme the way you want.

In the end you will end using both extensions at the same time to fix this scenario.

**Comment by tulios** [comment]
@zhoufenfens as @scudelletti pointed out, in json-viewer you can customize the style

![screen shot 2016-11-17 at 12 58 21](https://cloud.githubusercontent.com/assets/33231/20388546/a489f31a-acc5-11e6-8339-cc52d93f40bf.png)

@scudelletti nice combo, I still think it make sense to add this "whitelist" feature, but this combo sets the matter for now. Thanks!

**Comment by zzjin** [comment]
Same issue here, but do not want to install another plugin to modify header.
may be quickly test a `Content-Type:text/html;charset=UTF-8`'s content first 2 char is `{"` or someting could hadle it

**Comment by cevin** [comment]
@zzjin `["strings"]`

**Comment by tulios** [comment]
PR #117 should improve this behavior. I'll release a new version this week with the changes.
Thanks!

**Comment by tulios** [comment]
PR #117 was released on version 0.16.0 and should improve this behavior, closing this ticket for now
