### ISSUE TITLE
Unable to search for text in JSON in the JSON viewer mode

### ISSUE THREAD

**Issue by tariq1890** [tulios/json-viewer#129]
Hi Tulios,

Thanks for the great extension. I love the new mode you have added to view the JSON response. Would it be possible to do a Ctrl+F to search for text within the response like how we do so in the raw mode?

**Comment by tariq1890** [comment]
This is Invalid. my apologies

**Comment by tulios** [comment]
Hi @tariq1890, don't worry. JSON viewer has two "searches", the default one is a custom search since the extension doesn't render the whole JSON to improve performance and allow big files, but you can re-enable the browser search by setting `alwaysRenderAllContent` to `true`, just be aware that this will render all the content and it might be slow for big files.

**Comment by tariq1890** [comment]
Oh Sure. Thanks so much @tulios
