### ISSUE TITLE
Disable integrated search

### ISSUE THREAD

**Issue by mariussoutier** [tulios/json-viewer#42]
Could you please add an option to disable the integrated search? I know it supports regex, but sometimes the Chrome find command is just simpler to use / has better readability.

**Comment by tulios** [comment]
Hi @mariussoutier, you already is able to turn off the custom search, the problem is: to allow big files the plugin doesn't highlight all the content at once, it only highlights the visible part therefore it is impossible to the browser search to find anything that its not rendered. You can enable __ alwaysRenderAllContent__ and then JSON Viewer will render all the content and the custom search will be turned off, but be aware that large files could take a lot longer to load (there a people handling JSON files with +10MB)

The option that I mentioned is in the __add-ons__ section.

![addons](https://cloud.githubusercontent.com/assets/33231/8526938/0ce42070-240a-11e5-9fe8-4bd74ad47420.png)

**Comment by evvvritt** [comment]
Just to add, you can open Chrome's Find / Replace (and skip this extension's search) with `Find Next` (Cmd + G)
