### ISSUE TITLE
Theme with smaller font size

### ISSUE THREAD

**Issue by mariussoutier** [tulios/json-viewer#43]
I find the current themes waste too much space. Could you add a theme that is more compact with smaller font sizes? Ideally something that looks like GitHub.

Edit: Just realized you can customize font-size and font-face. Maybe just move the custom styling next to the theming :)

**Comment by tulios** [comment]
You've probably solved this by your own but I will leave an answer to help others who come here in the future. In JSON Viewer you can customize the themes with your own CSS, actually the font size and family is already outside of theme CSS. In the options page, in the bottom of the page, you will find the __Custom Style__ field, where you can then customize your theme.

![custom-style-pic](https://cloud.githubusercontent.com/assets/33231/8526788/00157af2-2409-11e5-98d7-c3e04bb04042.png)

Thanks.

**Comment by sloanlance** [comment]
Although this issue is closed and the font size can be specified by the user, I wish the default style didn't specify an absolute font-size.  It would be nice if `font-size` were set to `inherit` by default or used a relative size like `larger`.

Ideally, I'd like to see `CodeMirror` with `font-size: inherit;` and`CodeMirror-hints` with`font-size: smaller;`.
