### ISSUE TITLE
Error: contentExtractor: Unexpected token #

### ISSUE THREAD

**Issue by hieblmedia** [tulios/json-viewer#77]
Unexpected token #

For example: https://gist.githubusercontent.com/ahmedeshaan/56f190ae2227c3444dc0/raw/7e72e2f053e0b5779fa9214f10c85f5b380a5245/robots.txt

If the first # changed to another char. The error also occurs with the other char in erros message.

**Comment by tulios** [comment]
Thanks @hieblmedia. I'll take a look, something looks fishy.

**Comment by tulios** [comment]
The extension is checking if it's a "JSON" if chrome loads the raw content page. The idea of this simple check is to create a lightweight check to stop the extension loading for everything. I will improve this check to verify if it's a JSON, this is tricky because we have JSONP as well. I'll try to fix this soon.

Thanks again.

**Comment by tulios** [comment]
This error is fixed in version 0.14.0, thanks for the reporting.
